### PR TITLE
Add "financialData" to "info"

### PR DESCRIPTION
**Pull request by jemshit**
- Added `data.financialData` dictionary into `self._info` dictionary. It contains important data such as `totalDebt`, `quickRatio`, `debtToEquity`, `currentPrice`, `currentRatio` from Statistics page of stock
- Fixed `data.summaryDetail` being added twice into `self._info`
- Update `.gitignore` using [gitignore.io](gitignore.io). Contains rules for Python, PyCharm, VirtualEnv, MacOs, Windows, Linux. Otherwise all files of virtualenv is not ignored

Order of `defaultKeyStatistics`, `summaryDetail` matters, added comment.

### CODE REVIEW

**Comment by claudinho85** [comment]
Hi jemshit, is it in roadmap a kind of integration of all data about Statistics and Analisys as asked before? 
Is it feasable to retrieve that information from web scraping or not? 

I've noticed a weird behaviour on that page ...

Thanks a lot

**Comment by jemshit** [comment]
@claudinho85 Statistics are inside "info". I am not sure about Analysis

**Comment by jemshit** [comment]
Web scarping is done on (example) https://finance.yahoo.com/quote/AAPL and https://finance.yahoo.com/quote/AAPL/financials. When you right-click on browser page (firefox) and click "view page source", you see the whole data. If the data you want is there, then it is feasible to retreive

**Comment by claudinho85** [comment]
Unfortunately, info found on those pages are not present as written here https://github.com/ranaroussi/yfinance/issues/678 
but I could be wrong ... Actually I hope to be wrong :-) 

What about it?

**Comment by chinmayandhare** [comment]
Hi jemshit, is it possible to add shares outstanding data to income statement when we pull it so that we get it for currennt as well as previous years?

**Comment by jemshit** [comment]
> Hi jemshit, is it possible to add shares outstanding data to income statement when we pull it so that we get it for currennt as well as previous years?

I don't think so

**Comment by ranaroussi** [comment]
I've added the `financialData` item without merging the pull requests since I didn't want to pull in your `.gitignore` file :)

**Pull request closed without merging**
