### PR TITLE
Quarterly/yearly financials/cashflow/bsheet in 1 fetch

### PR DESCRIPTION
**Pull request by GregoryMorse**
The idea was already present in _get_fundamentals and here it is properly done out.  However, probably the _get_financial_translator routine should just be cached and hard-coded and updated as needed since those 2 JavaScript fetching calls are likely rarely ever changed and should at least be globally cached per day, etc.

### CODE REVIEW

**Comment by ranaroussi** [comment]
What are you trying to accomplish here?

**Comment by GregoryMorse** [comment]
> What are you trying to accomplish here?

1) Now the quarterly (not only yearly) financial data is retrieved and put in a Pandas Dataframe.

2) This also fetches all 3 financial data: cash flow, balance sheet and overall financials both yearly (which are done with 3 separate HTML retrievals) in one single page request.  However the method is a bit complicated since another JavaScript file contains a translation table to dig out the language strings.

3) It limits the amount of HTTP requests to Yahoo (though the JavaScript request for lookup table could just be hardcoded more than likely to avoid that whole _get_financial_translator function but it should be left as a code comment so it can be updated easier if it changes in the future).

Is it not working currently?

**Comment by GregoryMorse** [comment]
Solves #90 and #102

**Comment by GregoryMorse** [comment]
It is now timezone-aware, converts to float, uses efficient and correct, equivalent to other code datetime conversion with Pandas.

**Pull request closed without merging**
