### PR TITLE
Fix TZ cache exception blocking import

### PR DESCRIPTION
**Pull request by ValueRaider**
Hopefully fix TZ cache exception blocking import #1700

The Singleton pattern makes unit testing this tricky, so can someone affected try branch? @rickturner2001 

Also:
- relocate cache init lock
- add test for setTzCacheLocation()

### CODE REVIEW

**Comment by rickturner2001** [comment]
Just tested the code on a readonly docker container and it works just fine. I wanted to ask you bout _TzCacheDummy

since the tz cache is registered by `_get_ticker_tz` in `base.py`, what made you want to initialize a cache with an instance of either _TzCache or _TzCache dummy instead of simply returning the tz value in the evnet  that we don't have r/w access

what made you want to crate the Dummy class instead of doing something like this? 

```python
 def _get_ticker_tz(self, proxy, timeout):
        if self._tz is not None:
            return self._tz

        # assume this exists
        has_rw_permissions = utils.can_rw_to_fs()
        
        tz = None
        cache = None
        
        if has_rw_permissions:
            cache = utils.get_tz_cache()
            tz = cache.lookup(self.ticker)

            if tz and not utils.is_valid_timezone(tz):
                # Clear from cache and force re-fetch
                cache.store(self.ticker, None)
                tz = None

        if tz is None:
            tz = self._fetch_ticker_tz(proxy, timeout)

            if utils.is_valid_timezone(tz):
                # info fetch is relatively slow so cache timezone
                if has_rw_permissions:
                    cache.store(self.ticker, tz)
            else:
                tz = None

        self._tz = tz
        return tz
```

I think maybe the class makes it easier to test, but maybe you can shed some light on this. Thanks

**Comment by ValueRaider** [comment]
I didn't implement the sqlite architecture so couldn't answer. The person that did, seemed to know more about Python engineering than me so I didn't question design, but they aren't active anymore.
First implementation - #1105 
`_TzCacheDummy` - #1113

If I had to guess, maybe it's to avoid checking filesystem (`can_rw_to_fs`) every time need timezone. I believe the Python philosophy is, just try and catch exceptions, instead of meticulous if-else https://stackoverflow.com/a/7604717

**Comment by rickturner2001** [comment]
is anyone still working on this?

**Comment by ValueRaider** [comment]
I half forgot, half wasn't sure if you wanted changes.

**Pull request merged**
