### PR TITLE
Fix for institutional investors issue and added mutual fund holders to ticker

### PR DESCRIPTION
**Pull request by bradmetz**
This combines changes proposed across PRs #456, #430, #406, #397, #375, #371, #365, #337, #316, #305, #220, #215, #203, #196, #187, #168, #442, #428, #409, #388, #345, #339, #299.  

Also added unit tests which use tickers that were identified as causing some of the reported errors.  
Updated change log.
updated setup.

### CODE REVIEW

**Comment by asafravid** [comment]
How can one know when this Fix is ready such that pip update to yfinance shall include it?

**Comment by bradmetz** [comment]
Hello

Right now I am waiting on a review for my PR to fix this issue before I
merge.  I am a maintainer on GitHub but not pypi so I either need to be
added as a maintainer on pypi as well or the original author needs to cut
the release with the changes so they are incorporated in pip.  I'm hoping
to get this done shortly but right now I'm waiting on a response from the
original author.

So short answer as soon as I hear back.

If you subscribe to notifications on GitHub you should get the update when
I complete the merge.

Brad

**Review by admirallenny — COMMENTED** [review]
looks good on my side of things.

**Comment by saldea1996** [comment]
hi I am new to github. con someone tell me how to apply these fixes? thank you

**Pull request merged**
