### PR TITLE
feat/retry with fallback cookie and crumb

### PR DESCRIPTION
**Pull request by Jshen123**
retry with fallback cookie and crumb when default strategy failed

### CODE REVIEW

**Comment by ValueRaider** [comment]
This just looks like moving code around, nothing actually changed.

**Comment by Jshen123** [comment]
> This just looks like moving code around, nothing actually changed.

@ValueRaider Previously, the fallback only kicks in [when `get_cookie_basic` fails to get crumb ](https://github.com/ranaroussi/yfinance/blob/a064937dcdf14a99bc3aff5cb6a883f870a2017e/yfinance/data.py#L283C42-L283C42)

However, even when you successfully get the crumb (with default strategy), the request will still get 401 response for some users (including myself). And in this case, code will never attempt fallback.

What the change does is, in the event default crumb is retrieved but the response fails, [it will attempt the fallback cookie and crumb](https://github.com/Jshen123/yfinance/blob/b1022ae228088032c7fb408c0b5dd7f70c728e74/yfinance/data.py#L335)

**Comment by ValueRaider** [comment]
You're right, I thought `if response.status_code >= 400 ...` was just refactoring. Will merge after I squash my commits.

**Comment by ValueRaider** [comment]
My squash has broken the PR. Rather that recreate, can you post a git patch file to my PR and I'll integrate? Means I can keep squashing.

**Pull request closed without merging**
