### PR TITLE
Fetching ESG data for a ticker

### PR DESCRIPTION
**Pull request by keenborder786**
In reference to issue #1241 :

- Added an ESG module in the scrapper sub-package to collect ESG-related data for a ticker.
- Added the esg property for the ticker class in order to return the esg-related scores in form of the pandas data frame.

### CODE REVIEW

**Comment by keenborder786** [comment]
@ranaroussi please review

**Comment by ValueRaider** [comment]
Switched target to `dev` (https://github.com/ranaroussi/yfinance/discussions/1084)

**Comment by keenborder786** [comment]
Are their any changes you would like to suggest @ValueRaider

**Comment by ValueRaider** [comment]
Update `tests/ticker.py TestTicker`, I think you can figure out what to do. And maybe add a test for the returned data, to alert when code broken.

**Comment by keenborder786** [comment]
okay.

**Comment by ValueRaider** [comment]
Update `tests/ticker.py TestTicker` - specifically `test_badTicker & test_goodTicker`

**Comment by ValueRaider** [comment]
I've updated `test_goodTicker` and `test_badTicker`. `test_badTicker` is raising an exception on ESG data - instead it should print the error and continue running.

I've also looked at returned data. Can you drop the `ticker` field (unnecessary), and maybe convert to `dict`?

**Comment by keenborder786** [comment]
okay I will do it.

**Comment by keenborder786** [comment]
I have made the changes please review @ValueRaider

**Comment by ValueRaider** [comment]
Looking good. I've squashed commits so watch out.

I noticed Yahoo returns peers, I think `yfinance`should return them too. At a minimum the list of peer tickers. Let user decided to discard information.

**Comment by keenborder786** [comment]
Sorry I don't understand what you mean by peers. Do you want me to make any more changes?

**Comment by ValueRaider** [comment]
`self._sustainability_data['ESGStore']["peerScores"]`

**Comment by keenborder786** [comment]
okay let me see.

**Comment by ValueRaider** [comment]
I know I suggested switch to `dict`, but with multiple tickers a `DataFrame` might be better. Best if you decide because I'm assuming you need this feature.

**Comment by keenborder786** [comment]
I have added the peer scores so now returned dict will have ticker scores + peer scores in form of list in the returned dict. please have a look @ValueRaider

**Comment by ValueRaider** [comment]
Ok good. I updated README.

When I said "squash commits", that means you have to re-clone your repo. Because I've overwritten your git history. Not fix conflicts.

**Comment by ValueRaider** [comment]
Your DataFrame is worse. When I suggested a DataFrame, I meant one ticker per row, a simple table.

**Comment by keenborder786** [comment]
okay. I feel like, what I will do is create a data frame with multiple rows. One row for the ticker and other for peers. Does this sound fair?

**Comment by ValueRaider** [comment]
Take more care in your code, think what is best for users.

**Comment by keenborder786** [comment]
ok. This time, I will make it a user-friendly dataframe with clear information.

**Pull request closed without merging**
