### PR TITLE
update start parameter docstring

### PR DESCRIPTION
**Pull request by lucas03**

### CODE REVIEW

**Comment by lucas03** [comment]
hey @ValueRaider, will this get released or are you waiting for that wiki MR? :P

**Comment by ValueRaider** [comment]
Mostly me being lazy, but should coordinate merge with Wiki update - can you update?

**Comment by lucas03** [comment]
you're not lazy, I see how you actively resolve issues even though people don't read and report the same over again,  thank you for that!

I updated default here - https://github.com/ranaroussi/yfinance/wiki/Ticker

**Comment by ValueRaider** [comment]
Ah, I forgot this involved a code change. I can merge but not keen on another release just for this - will you be happy with a beta? I can upgrade to official if more people report problem.

**Comment by lucas03** [comment]
Up to you, I guess I can handle a few more errors in sentry

**Comment by lucas03** [comment]
up to you :)

**Comment by lucas03** [comment]
will beta release appear here? https://github.com/ranaroussi/yfinance/releases

**Comment by ValueRaider** [comment]
done

**Pull request merged**
