### PR TITLE
Adding various financials to const.py

### PR DESCRIPTION
**Pull request by rhwvu**
This adds "OccupancyAndEquipment", "ProfessionalExpenseAndContractServicesExpense", and "OtherNonInterestExpense" to the financials in const.py, which are all found on AXP's (American Express) income statement on Yahoo. This also adds the various expenses from [vittoboa's issue](https://github.com/ranaroussi/yfinance/pull/1965) which I already made the [issue](https://github.com/ranaroussi/yfinance/issues/1961) on. It also adds the balance-sheet name "CashCashEquivalentsAndFederalFundsSold" which AXP uses for its cash.

### CODE REVIEW

**Comment by ValueRaider** [comment]
[rebase to dev](https://github.com/ranaroussi/yfinance/discussions/1084)

**Comment by rhwvu** [comment]
When trying to do the rebase, with the `git push --force-with-lease origin main` command, I get the following error:
`remote: Permission to ranaroussi/yfinance.git denied to rhwvu.
fatal: unable to access 'https://github.com/ranaroussi/yfinance.git/': The requested URL returned error: 403`
How do I go about fixing this? I did the rebase command successfully.

**Comment by ValueRaider** [comment]
Did you clone this repo by mistake? The force push should work in your cloned fork, because it's yours.

**Comment by rhwvu** [comment]
Ok, starting over, with `git rebase --onto dev main main` I get the following error:
`fatal: Does not point to a valid commit 'dev'`
Is this because I need to point to or clone the dev branch of the origin yfinance? Currently I've only cloned the main branch.

**Comment by ValueRaider** [comment]
https://openai.com/chatgpt

**Pull request closed without merging**
