### PR TITLE
Fix `history_metadata` accesses for unusual symbols

### PR DESCRIPTION
**Pull request by sdeibel**
Fix format_history_metadata when firstTradeDate is None, as is the case for QCSTIX and probably others.  Submitting this on main since it seemed appropriate for that based on the instructions in https://github.com/ranaroussi/yfinance/discussions/1084 -- I can redo it if that is not what you want.

### CODE REVIEW

**Comment by ValueRaider** [comment]
`main` is fine for this. I've updated unit tests (they should have detected problem), which found some other issues. I don't have time to use, let me know if anything broken.

**Comment by sdeibel** [comment]
I don't think there are new problems but found that requirements.txt was missing requests-cache and scipy so I updated this pull request.  Actually, I meant to make a new separate pull request but that didn't got as planned...

**Comment by ValueRaider** [comment]
Those two modules aren't *necessary* so deliberately missing.
- `requests_cache` - if user smart enough to want to cache, they're smart enough to install
- `scipy` - my sense is usage of price repair is rare (where `scipy` used)

**Comment by sdeibel** [comment]
There were needed to run the unit tests, which is what motivated me to add them.  I suppose another idea would be to add a requirements-test.txt but it's not a big deal since it's pretty obvious what's needed when trying to run the tests and only two things had to be installed.

**Comment by ValueRaider** [comment]
I deleted that commit

**Comment by sdeibel** [comment]
Great, thanks.

**Pull request merged**
