### PR TITLE
[BUG] Fix failure when using single ISIN as a ticker (#1525)

### LINKED ISSUE #1525: Falure when using single ISIN as a ticker (fix included)
Multiple tickers with ISINs mixed in do work, but a single ISIN fails. Here is the culprit (multi.py):

>     if len(tickers) == 1:
>        ticker = tickers[0]
>        return shared._DFS[shared._ISINS.get(ticker, ticker)]

The last line should be just

> return shared._DFS[ticker]

as at that point in time both _DFS and tickers refer to Yahoo ID instead of ISIN, and lookup by original ISIN in _DFS is failing. 

Testcase:

>import yfinance as yf
>yf.download("SE0000594111", period="7d", repair=True, progress=False, threads=False, timeout=30)

(corresponding Yahoo ID is '0P00000FYR.ST'.

### PR DESCRIPTION
**Pull request by ricardoprins**
Fix #1525, #898.

I am submitting this directly to main since this bug is already in production.

### CODE REVIEW

**Comment by ValueRaider** [comment]
Great. Can you search through [other ISIN issues](https://github.com/ranaroussi/yfinance/issues?q=is%3Aissue+is%3Aopen+isin) and add if fixed

**Comment by ricardoprins** [comment]
Sure, I'll take a look at it.

**Comment by ricardoprins** [comment]
So, I found 8 related issues; I'll go through them one at a time, and I'll post the corresponding conclusions for the tests inside each of the issues. It will take me a few days to set up the proxy for the ones involving proxy connection, but I'll try to get these done as well. Hope it helps!

**Comment by ValueRaider** [comment]
Oh don't worry about the proxy ones, I just meant see if this PR fixes other issues. Duplicate issues are common.

**Comment by ricardoprins** [comment]
That works for me. From a quick glance, though, it seems that the proxy issues are already fixed. I have some free time on my hands, I'll "sit around" in this repo for a while :)

**Comment by ricardoprins** [comment]
Fixes #898 as well.

**Pull request merged**
