### PR TITLE
Bugfix/data types

### PR DESCRIPTION
**Pull request by mreiche**
Fixes bug:
```
ERROR:yfinance:XXX: No timezone found, symbol may be delisted
ERROR:xxx:'list' object has no attribute 'loc'
```

### CODE REVIEW

**Comment by ValueRaider** [comment]
I'm struggling to understand the problem. Can you submit a bug report using template?

**Comment by mreiche** [comment]
> I'm struggling to understand the problem. Can you submit a bug report using template?

The interface says that a ‚pandas.Series‘ is returned, which is not true when the relation is empty.

**Comment by ValueRaider** [comment]
I understand now. Unit tests would be good. Also, please target `dev` branch not `main` #1084

**Comment by ValueRaider** [comment]
Can you also rebase to `dev`, tidy up the commit history.

**Comment by mreiche** [comment]
I did already. It tells me that i'ts already update. I don't unterstand what happend here.

**Comment by ValueRaider** [comment]
You changed the target but haven't rebased. Look at the diff.

**Comment by mreiche** [comment]
I rebased again and force pushed. Hope that helps. Sorry, I'm not experience with rebase. I only merge branches.

**Comment by ValueRaider** [comment]
Not knowing is fine, but you aren't rebasing. Look at the diff, did you mean to change the version?

**Comment by mreiche** [comment]
```bash
$ git branch
* bugfix/data-types
  main

$ git remote -v
origin  https://github.com/mreiche/yfinance.git (fetch)
origin  https://github.com/mreiche/yfinance.git (push)
yfinance        https://github.com/ranaroussi/yfinance.git (fetch)
yfinance        https://github.com/ranaroussi/yfinance.git (push)

$ git log -n 4
commit 77e7be7f8d0c826caa5eefbd8c0d572dad3e080d (HEAD -> bugfix/data-types, origin/bugfix/data-types)
Author: Mike Reiche
Date:   Tue Oct 10 08:25:47 2023 +0200

    Added tests

commit 6b400aaacb91b1bba3818be606650b57cec98114
Author: Mike Reiche
Date:   Mon Oct 9 09:59:25 2023 +0200

    Minor typing fixes

commit c4965fa451f50645cecfab359098f49799a6c0f9
Author: Mike Reiche
Date:   Mon Oct 9 09:53:57 2023 +0200

    Fixed typing bug when series are empty

commit 16305dd7f3175676e15eb6bbfdae73f04b8100c0
Author: Value Raider
Date:   Wed Oct 4 22:03:24 2023 +0100

    Bump version to 0.2.31
$ git fetch yfinance
$ git rebase yfinance/dev
Current branch bugfix/data-types is up to date.
$ git push --force
Everything up-to-date
```
What I'm doing wrong?

**Comment by mreiche** [comment]
ChatGPT:
> Ah, the mysterious case of the unclaimed commit! When you rebase a branch in Git, you're essentially rewriting the commit history. If you find a commit that seems unfamiliar, it might be a result of conflict resolution during the rebase process.

> When Git encounters a conflict during rebase, it pauses and asks you to resolve it. If you're not careful, it's easy to accidentally include changes from the wrong commit or overlook something. This could lead to committing changes that weren't originally yours.

> To investigate, you can use `git log` to examine the commit history and `git reflog` to see the history of branch references. Look for any signs of a merge conflict or unusual commits.

> To fix it, you might need to:

> 1. **Identify the incorrect commit:** Check the commit message, changes, and authorship to figure out which commit is the culprit.

> 2. **Amend or revert the commit:** Depending on the situation, you can either amend the commit with the correct changes or revert the commit entirely and then reapply the correct changes.

> Remember, it's always a good practice to double-check your changes during a rebase to avoid such surprises. Git can be a tricky beast, but with a bit of detective work, you can usually straighten things out!

Can't you just ignore and merge it?

**Comment by mreiche** [comment]
Ok, I paid the monthly subscription for ChatGPT 4. Quote:
> Feel free to go ahead and merge the rebased branch into the target branch when you're ready. If you have any specific concerns or questions about the process, feel free to ask!

**Comment by ValueRaider** [comment]
Now tell it the commit history still leads back to "main".

**Comment by mreiche** [comment]
I tell you what. I create a new PR and cherry pick my commits.

**Pull request closed without merging**
