### PR TITLE
Fix stores decrypt

### LINKED ISSUE #1291: Scraper error "TypeError: string indices must be integers"  - Yahoo decrypt fail
### 2023 January 13
By the time of posting the issue (2023 January 12), the issue only occured sometimes. The library is now (2023 January 13) completely broken and I am unable to retrieve any stock informatio
### 2023 January 14
Fix has been merged to the branch `dev`

## Info about your system:
yfinance version: 0.2.3
Operating system: macOS Monteray 12.0.1
### Snippet that can recreate the error
```
stock = yf.Ticker("^GSPC")
info = stock.info
```
## Error
Message:`TypeError: string indices must be integers`
It seems to be a problem where the scraper is not scraping the correct information, leading to a crash.
### Traceback:
```
Traceback (most recent call last):
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/2022/szhang139/repos/STONK/src/main.py", line 61, in notify
    market = get_major_index(f'Market Close - {daytime.today_date()}')
  File "/home/2022/szhang139/repos/STONK/src/market_info.py", line 63, in get_major_index
    sp500 = get_stock('^GSPC')
  File "/home/2022/szhang139/repos/STONK/src/market_info.py", line 41, in get_stock
    stock_info = get_stock_info(stock_name)
  File "/home/2022/szhang139/repos/STONK/src/market_info.py", line 8, in get_stock_info
    info = stock.info
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/ticker.py", line 138, in info
    return self.get_info()
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/base.py", line 894, in get_info
    data = self._quote.info
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 27, in info
    self._scrape(self.proxy)
  File "/home/2022/szhang139/.local/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 58, in _scrape
    quote_summary_store = json_data['QuoteSummaryStore']
```
### Frequency
The error occurs in no apparent pattern. Every time it occurs, it seem to persist for some range of time before it recovers back to normal.
n.

### PR DESCRIPTION
**Pull request by alexa-infra**
Should fix #1291

### CODE REVIEW

**Comment by SamZhang02** [comment]
This seems to work on my local, thanks for the fix :)

**Comment by andrewkenreich** [comment]
My worry here is you are assuming that the key is just not the other two values in the dict - what if they add another key to that dict eventually? Could we check for the key value that is 128 char long? 

Would still break when they change encryption off 128 but prevents if they added future things to the dict not related to this. (Also since you are already preventing if they change the name of this key)

For now though this works. This will probably be a cat and mouse game for awhile.

**Comment by ValueRaider** [comment]
Restored the `"_cr" and "_cs"` code path, in case `data` is coming from `requests_cache`.

**Comment by ValueRaider** [comment]
@andrewkenreich I've incorporated your feedback, so `yfinance` should print a useful message if format changes again.

**Comment by ValueRaider** [comment]
Can I get confirmation that this works with my changes? Then will merge.

**Comment by dschaefer** [comment]
Worked for me.

**Comment by ValueRaider** [comment]
Great, merged into `dev`. Would be great if you can switch to `dev` and act as beta testers for me, as some other changes there.

`dev` = I believe is stable but needs stress-testing

**Comment by dschaefer** [comment]
Already done :). Looks good. Thanks!

**Comment by james-stevens** [comment]
Well done, great work 

If I was doing the code review (which I'm not, so ignore me as you please) I'd say a couple of things
1. probably be neater to make `decode_password` a separate function (lines 52 to 75)
2. seems to me `if k not in ["context", "plugins"]]` is vulnerable to breaking, so maybe a function that looks for appropriate looking hex strings might be more robust - but who knows what they will do in the future, so also maybe not

**Comment by no0be** [comment]
Thanks everyone for the quick fix, just upgraded to the 0.2.4 package from pip3 and I confirm it works fine.

**Comment by cameroncochrane** [comment]
Thank you for fixing, much appreciated :)

**Comment by Sathiya-K** [comment]
> This seems to work on my local, thanks for the fix :)

Can you please explain how did you fix it? I upgraded my yfinance to 0.1.93. Thanks in advance!

**Comment by Sathiya-K** [comment]
> Thanks everyone for the quick fix, just upgraded to the 0.2.4 package from pip3 and I confirm it works fine.

Upgraded the yfinance library is it?

**Pull request merged**
