### PR TITLE
Added property getting company executives

### PR DESCRIPTION
**Pull request by nikolamilosevic86**
I have added a functionality that reads company executives with their salaries and dates of births if available. The retrieved information comes in dataframe in property executives.

### CODE REVIEW

**Comment by ProgrammingDao** [comment]
Happy to help with the review if appropriate.

**Comment by ValueRaider** [comment]
Hi Nikola. I'm willing to merge but have one request - move the fetching into it's own function e.g. `Ticker._get_executives()`. Each scrape url should have its own function.

**Comment by fredrik-corneliusson** [comment]
@ValueRaider if merged please make sure it does not affect performance of other API:s
New features should be carefully added and be of common use as all new features need to be maintained and supported.

In my opinion before adding more features to the already bloated and buggy `base.py` the code need to restructured to allow for a more plugin oriented API.

**Comment by nikolamilosevic86** [comment]
This is now obsolete

**Pull request closed without merging**
