### PR TITLE
Fix proxy arg passthrough

### LINKED ISSUE #998: No data found for this date range, symbol may be delisted(July 26th,2022): But, it works again now
I run yfiance codes, and it went well before!
Also, I checked the same Issues which other friends talked about. It is not helpful.
My codes as fellow:

StartDate="2022-05-16"
EndDate="2022-05-23"

SYMBOL="QQQ"
data=yf.Ticker(SYMBOL)

DATE_CHECK=data.history(interval="1m",start=StartDate,end=EndDate)

print(DATE_CHECK)
sys.exit(0)

Errors show as fellow:

- QQQ: No data found for this date range, symbol may be delisted
Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume, date]
Index: []
[Finished in 2.1s]

Somebody to help me?

### PR DESCRIPTION
**Pull request by ValueRaider**
`proxy` argument was broken in recent versions, this should fix it. 

Fixes #998 #1282 #1386, and maybe #1387 (were they using proxy?)

### Status

`Ticker.isin()` doesn't work with proxy, can someone with a proxy help investigate? #1399

### CODE REVIEW

**Comment by ValueRaider** [comment]
@ricardoprins Start your proxy testing here.

**Comment by ricardoprins** [comment]
This fixes #1399. Going to check the other open issues.

```python
def test_ticker_with_proxy(self):
        proxy = 'http://xxx.xxx.xxx.xxx:xxxxx' (address omitted on purpose here)
        ticker = yf.Ticker('AAPL')
        isin = ticker.get_isin(proxy)
        assert isin is not None
```

test results:
```bash
Testing started at 2:56 PM ...
Launching unittests with arguments python -m unittest test_yfinance.TestTicker.test_ticker_with_proxy in xxxxx

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /v6/finance/quoteSummary/AAPL?modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query1.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query1.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/AAPL?symbol=AAPL&type=trailingPegRatio&period1=1673913600&period2=1689724800 HTTP/1.1" 200 247
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): markets.businessinsider.com:443
DEBUG:urllib3.connectionpool:https://markets.businessinsider.com:443 "GET /ajax/SearchController_Suggest?max_results=25&query=Apple%20Inc. HTTP/1.1" 200 3817


Ran 1 test in 1.733s

OK

```

**Comment by ricardoprins** [comment]
This fixes #1386:

```python
    def test_download_with_proxy(self):
        proxy = 'http://xxx.xxx.xxx.xxx:xxxxx' # (address omitted on purpose here) 
        download = yf.download('AAPL', proxy=proxy)
        assert download is not None
```

test results:
```bash
Testing started at 2:57 PM ...
Launching unittests with arguments python -m unittest test_yfinance.TestTicker.test_download_with_proxy in xxxxx

DEBUG:yfinance:Entering download()
DEBUG:yfinance:Disabling multithreading because DEBUG logging enabled
DEBUG:yfinance: Entering history()
DEBUG:yfinance:AAPL: Yahoo GET parameters: {'period1': '1899-12-31 17:24:11-04:56', 'period2': '2023-07-18 16:57:46-04:00', 'interval': '1d', 'includePrePost': False, 'events': 'div,splits,capitalGains'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /v8/finance/chart/AAPL?period1=-2208994789&period2=1689713866&interval=1d&includePrePost=False&events=div%2Csplits%2CcapitalGains HTTP/1.1" 200 None
DEBUG:yfinance:AAPL: yfinance received OHLC data: 1980-12-12 14:30:00 -> 2023-07-18 20:00:04
DEBUG:yfinance:AAPL: OHLC after cleaning: 1980-12-12 09:30:00-05:00 -> 2023-07-18 16:00:04-04:00
DEBUG:yfinance:AAPL: OHLC after combining events: 1980-12-12 00:00:00-05:00 -> 2023-07-18 00:00:00-04:00
DEBUG:yfinance:AAPL: yfinance returning OHLC: 1980-12-12 00:00:00-05:00 -> 2023-07-18 00:00:00-04:00
DEBUG:yfinance: Exiting history()
DEBUG:yfinance:Exiting download()


Ran 1 test in 0.662s

OK


```

**Review by ricardoprins — APPROVED** [review]
It seems to me that this has solved the proxy issue.

**Pull request merged**
