### PR TITLE
Fix timezone & datetime handling

### PR DESCRIPTION
**Pull request by ValueRaider**
This big update fixes all problems related to timezones:
1. Convert Yahoo datetimes from UTC into timezone of exchange [#978](https://github.com/ranaroussi/yfinance/issues/978) [#1010](https://github.com/ranaroussi/yfinance/issues/1010)
2. If user provided timezone-naive datetimes then assume they mean timezone of exchange [#1010](https://github.com/ranaroussi/yfinance/issues/1010)
3. Use `datetime` module for epoch read/write instead of `time` [#954](https://github.com/ranaroussi/yfinance/issues/954) [#949](https://github.com/ranaroussi/yfinance/issues/949)
4. Yahoo can mess up DST so day start time is off by an hour - e.g. Brazil around Jan-2022 is 23:00 instead of 00:00. So detect and adjust to 00:00
5. Process user-provided `tz` argument correctly - use it to convert, not localize

This requires knowing exchange timezone, which means looking up `Ticker.info[]` but that's expensive! Splitting `info[]` creation out of `_get_fundamentals()` into `_get_info()` helped but still slow. So solution is to cache the timezone in users cache folder, because why would it change?

I've been using this personally for a month now, no problems.

Will fix these issues: [#971](https://github.com/ranaroussi/yfinance/issues/971)

These issues probably fixed too (difficult to test): [#890](https://github.com/ranaroussi/yfinance/issues/890) [#871](https://github.com/ranaroussi/yfinance/issues/871) [#805](https://github.com/ranaroussi/yfinance/issues/805) [#413](https://github.com/ranaroussi/yfinance/issues/413)

### CODE REVIEW

**Comment by ValueRaider** [comment]
Regarding CodeFactor issue - everything it says applies to the pre-existing `_get_fundamentals()` method, so not my fault.

**Comment by ValueRaider** [comment]
@asafravid I forgot to ask - do you use Windows? If yes can you quickly test code for me, I only tested caching on Linux. It should work on all platforms.

**Comment by asafravid** [comment]
@ValueRaider sure
Send me the commands to execute

**Comment by ValueRaider** [comment]
https://github.com/yfinance-fork-team/yfinance-x/discussions/14

**Comment by ValueRaider** [comment]
@asafravid I meant can you actually _use_ yfinance for simple price data fetches. Obviously it won't break at import.

**Comment by ValueRaider** [comment]
```
yf.Ticker("INTC").history(start="2022-08-01")
yf.Ticker("INTC").history(start="2022-08-01")
```

**Comment by asafravid** [comment]
All good
----------

Test script:

    result1 = yf.Ticker("INTC").history(start="2022-08-01")
    result2 = yf.Ticker("INTC").history(start="2022-08-01")
    print(result1)
    print(result2)

Result:

                     Open       High        Low  ...    Volume  Dividends  Stock Splits
    Date                                         ...                                   
    2022-08-01  35.689698  37.313306  35.689698  ...  52513400      0.000             0
    2022-08-02  36.224302  36.293602  35.640198  ...  53929400      0.000             0
    2022-08-03  35.729300  36.224303  34.907594  ...  59513900      0.000             0
    2022-08-04  36.009998  36.099998  35.360001  ...  54046300      0.365             0
    2022-08-05  35.349998  35.689999  35.180000  ...  40205100      0.000             0
    2022-08-08  35.360001  35.959999  35.200001  ...  41534600      0.000             0
    2022-08-09  35.220001  35.299999  34.400002  ...  48202300      0.000             0
    2022-08-10  34.990002  35.400002  34.590000  ...  42243300      0.000             0
    2022-08-11  35.639999  36.290001  35.490002  ...  35569700      0.000             0
    2022-08-12  35.799999  36.139999  35.669998  ...  37675200      0.000             0
    2022-08-15  36.099998  36.430000  35.709999  ...  25400600      0.000             0
    2022-08-16  36.160000  36.580002  35.700001  ...  25000200      0.000             0
    2022-08-17  35.810001  36.080002  35.270000  ...  29176100      0.000             0
    2022-08-18  35.680000  36.330002  35.570000  ...  24598200      0.000             0
    2022-08-19  35.799999  36.029999  35.189999  ...  31425500      0.000             0
    2022-08-22  35.000000  35.060001  33.730000  ...  51006100      0.000             0
    2022-08-23  33.980000  34.389999  33.910000  ...  30687100      0.000             0
    2022-08-24  33.970001  33.990002  33.599998  ...  25105700      0.000             0
    2022-08-25  33.869999  34.930000  33.820000  ...  29799100      0.000             0
    2022-08-26  34.950001  35.029999  33.349998  ...  44851500      0.000             0
    2022-08-29  33.230000  33.410000  32.810001  ...  32976800      0.000             0
    2022-08-30  33.040001  33.070000  32.150002  ...  40182500      0.000             0
    2022-08-31  32.389999  32.389999  31.770000  ...  44074500      0.000             0
    2022-09-01  31.570000  31.830000  31.129999  ...  36440700      0.000             0
    2022-09-02  32.209999  32.380001  31.059999  ...  34871100      0.000             0
    2022-09-06  31.389999  31.389999  30.330000  ...  46989600      0.000             0
    2022-09-07  30.420000  30.790001  30.049999  ...  37329500      0.000             0
    2022-09-08  30.370001  30.850000  29.910000  ...  37359500      0.000             0
    2022-09-09  31.190001  31.500000  31.080000  ...  34069500      0.000             0
    2022-09-12  31.740000  31.860001  31.100000  ...  38305500      0.000             0
    2022-09-13  30.830000  30.930000  29.250000  ...  71417900      0.000             0
    2022-09-14  29.549999  29.770000  29.010000  ...  40767200      0.000             0
    2022-09-15  29.150000  29.410000  28.709999  ...  39919100      0.000             0
    2022-09-16  28.700001  29.320000  28.420000  ...  72687900      0.000             0
    2022-09-19  29.020000  29.500000  28.900000  ...  33151900      0.000             0
    2022-09-20  29.070000  29.170000  28.709999  ...  31097600      0.000             0
    2022-09-21  29.150000  29.320000  28.639999  ...  16936722      0.000             0
    
    [37 rows x 7 columns]
                     Open       High        Low  ...    Volume  Dividends  Stock Splits
    Date                                         ...                                   
    2022-08-01  35.689698  37.313306  35.689698  ...  52513400      0.000             0
    2022-08-02  36.224302  36.293602  35.640198  ...  53929400      0.000             0
    2022-08-03  35.729300  36.224303  34.907594  ...  59513900      0.000             0
    2022-08-04  36.009998  36.099998  35.360001  ...  54046300      0.365             0
    2022-08-05  35.349998  35.689999  35.180000  ...  40205100      0.000             0
    2022-08-08  35.360001  35.959999  35.200001  ...  41534600      0.000             0
    2022-08-09  35.220001  35.299999  34.400002  ...  48202300      0.000             0
    2022-08-10  34.990002  35.400002  34.590000  ...  42243300      0.000             0
    2022-08-11  35.639999  36.290001  35.490002  ...  35569700      0.000             0
    2022-08-12  35.799999  36.139999  35.669998  ...  37675200      0.000             0
    2022-08-15  36.099998  36.430000  35.709999  ...  25400600      0.000             0
    2022-08-16  36.160000  36.580002  35.700001  ...  25000200      0.000             0
    2022-08-17  35.810001  36.080002  35.270000  ...  29176100      0.000             0
    2022-08-18  35.680000  36.330002  35.570000  ...  24598200      0.000             0
    2022-08-19  35.799999  36.029999  35.189999  ...  31425500      0.000             0
    2022-08-22  35.000000  35.060001  33.730000  ...  51006100      0.000             0
    2022-08-23  33.980000  34.389999  33.910000  ...  30687100      0.000             0
    2022-08-24  33.970001  33.990002  33.599998  ...  25105700      0.000             0
    2022-08-25  33.869999  34.930000  33.820000  ...  29799100      0.000             0
    2022-08-26  34.950001  35.029999  33.349998  ...  44851500      0.000             0
    2022-08-29  33.230000  33.410000  32.810001  ...  32976800      0.000             0
    2022-08-30  33.040001  33.070000  32.150002  ...  40182500      0.000             0
    2022-08-31  32.389999  32.389999  31.770000  ...  44074500      0.000             0
    2022-09-01  31.570000  31.830000  31.129999  ...  36440700      0.000             0
    2022-09-02  32.209999  32.380001  31.059999  ...  34871100      0.000             0
    2022-09-06  31.389999  31.389999  30.330000  ...  46989600      0.000             0
    2022-09-07  30.420000  30.790001  30.049999  ...  37329500      0.000             0
    2022-09-08  30.370001  30.850000  29.910000  ...  37359500      0.000             0
    2022-09-09  31.190001  31.500000  31.080000  ...  34069500      0.000             0
    2022-09-12  31.740000  31.860001  31.100000  ...  38305500      0.000             0
    2022-09-13  30.830000  30.930000  29.250000  ...  71417900      0.000             0
    2022-09-14  29.549999  29.770000  29.010000  ...  40767200      0.000             0
    2022-09-15  29.150000  29.410000  28.709999  ...  39919100      0.000             0
    2022-09-16  28.700001  29.320000  28.420000  ...  72687900      0.000             0
    2022-09-19  29.020000  29.500000  28.900000  ...  33151900      0.000             0
    2022-09-20  29.070000  29.170000  28.709999  ...  31097600      0.000             0
    2022-09-21  29.150000  29.320000  28.639999  ...  16936722      0.000             0
    
    [37 rows x 7 columns]
    
    Process finished with exit code 0

**Pull request merged**
