### PR TITLE
Fix timestamp overflow issue

### PR DESCRIPTION
**Pull request by ymyke**
See https://github.com/ranaroussi/yfinance/issues/1199

### CODE REVIEW

**Comment by ValueRaider** [comment]
With this fix what is the oldest data returned for ticker "^GSPC"? I can go back to 1927.

**Comment by ymyke** [comment]
1970-01-02

**Comment by ValueRaider** [comment]
Need to go before 1970. Read this https://stackoverflow.com/a/41965216

**Comment by fredrik-corneliusson** [comment]
I think this is already fixed as part of fix of #1171
https://github.com/ranaroussi/yfinance/issues/1171#issuecomment-1328076245

Running windows I cannot reproduce the error in dev.

**Comment by ValueRaider** [comment]
@fredrik-corneliusson I agree

**Comment by ymyke** [comment]
I verified and agree to. Branch deleted.

**Pull request closed without merging**
