### PR TITLE
Fix wrong data for yearly and quarterly EBIT

### PR DESCRIPTION
**Pull request by aliencaocao**
This is a quick & dirty fix. It currently ignores custom headers and proxies that the user may set.

It uses the API directly to get data instead of the current HTML parsing way. This way can get much more data, but it is too much work to migrate to API for all the data, so I just fixed the EBIT field as many have reported the issue.

If you would like me to work on migrating to the new API, I am happy to help, but can only start working on it in December. This API way works for income statements, balance sheet and cashflow, both quarterly and yearly and TTM.

Hope it will get merged soon to help out numerous people facing the issue. I know there are similar fixes but they are all larger scaled so takes longer to test and merge.

Fixes https://github.com/ranaroussi/yfinance/issues/1044 https://github.com/ranaroussi/yfinance/issues/1004 (EBIT part of it but the rest can also be fixed by similar method) https://github.com/ranaroussi/yfinance/issues/844 https://github.com/ranaroussi/yfinance/issues/1079

### CODE REVIEW

**Comment by ValueRaider** [comment]
We're currently working on a broader fix, although not using that url for everything. Currently in `dev` branch undergoing testing. If you try it and find issues put them here: https://github.com/ranaroussi/yfinance/discussions/1081

**Comment by ValueRaider** [comment]
That's a question for @git-shogg. I think their reason is via-html enables reproduction of the nested structure, but via API just provides string-value.

**Comment by aliencaocao** [comment]
Ok, that makes sense to me, although I personally do not think keeping the nested structure will be helpful to anyone, since, from a quantitive analysis usage standpoint, the user would just need the numerical data of the particular field, but does not really care where it belongs under, that is more for financial knowledge not for quantitative analysis.
Still, it introduces unnecessary complexity and slowdowns in code since regex and json parsing are both slow.

**Comment by ValueRaider** [comment]
That was my thought too (complexity), but @git-shogg feels strongly that nested structure is useful for DCF: https://github.com/ranaroussi/yfinance/pull/776#issuecomment-1279914639

I'll create a thread in the discussion on this.

**Comment by aliencaocao** [comment]
Alright. I shall close this PR then, since it is already implemented in dev branch. Thanks!

**Pull request closed without merging**
