### PR TITLE
ticker info docs

### PR DESCRIPTION
**Pull request by 0silverback0**
Would this be  a good start for documentation of the Ticker.info key definitions. If so I can continue on

### CODE REVIEW

**Comment by 0silverback0** [comment]
I was addressing issue #632 about documentation for the keys returned from Ticker.info()

**Comment by ValueRaider** [comment]
Ok. But before diving into documenting first need to think carefully about design. E.g.
- I see a lot of copy-pasting Investopedia - why not just link directly?
- Where to put documentation? In another Python data structure? On website?

**Comment by 0silverback0** [comment]
I was thinking the documentation for this particular information would be a page in root in order to keep the look as clean as possible.

I left the synopsis and link for the developer to be able to research in more depth if need be. 

I believe providing the developer with as much information possible as to how to interact with your API is the responsibility of the API owner.

**Comment by fredrik-corneliusson** [comment]
Keep in mind that if it's documentation from other sources it has to have a open source license permitting copying. If not it would  probably result in a copyright violation.

**Comment by 0silverback0** [comment]
> Keep in mind that if it's documentation from other sources it has to have a open source license permitting copying. If not it would  probably result in a copyright violation.

I believe investopedia is ok but I will double check it and make necessary changes. I would like to know if this is something that is still wanted before I continue working?

**Comment by fredrik-corneliusson** [comment]
Hi, I think with every new bit in information we add it will have to be supported and updated causing extra work for current maintainer. If there are good external sources for that information elsewhere maybe it would be better to document where to find it?
But what I think is really needed is updated documentation for the yfinance API (in the readme and or docstrings). Especially for the upcoming 0.2 changes in Dev branch that has changed quite a bit.

**Comment by 0silverback0** [comment]
Ok I'll take a look at it and if I can handle it I'll get right to work on that

**Comment by CollieIsCute** [comment]
@ValueRaider  Aside from Ticker.info, I think it'll be awesome if we make a github wiki which record all api of yfinance, such as
- Definition and meaning of each parameters within yfinance.
- Type of return objects

With the docs, newbies like me could spend less time tracing source code. I spent much time reading source code to find out something like "what's difference between `download()` and  `history()`" and "Which is more efficient when iterating? List of Ticker objs or Tickers obj?"

**Comment by ValueRaider** [comment]
@CollieIsCute Good point but is different to this PR. Can you raise in another Issue/PR, and maybe someone can volunteer to improve API doc.

**Comment by ValueRaider** [comment]
Wiki is live so this should go into Wiki

**Pull request closed without merging**
