### PR TITLE
Fix "unauthorized, invalid crumb"

### PR DESCRIPTION
**Pull request by signifer-geo**
It fixes the error: unauthorized, invalid crumb

### CODE REVIEW

**Comment by ValueRaider** [comment]
Confirmed fix for #1592

**Comment by ValueRaider** [comment]
I see the url has changed, but what do the changes to `params` mean?

**Comment by signifer-geo** [comment]
It works for v6 api instead of for v10. Maybe a temporary fix, but it seems to work. Changes to params due to what seems to be a different format between v6 and v10.

This doesn't work anymore:

https://query2.finance.yahoo.com/v10/finance/quoteSummary/AMD?modules=summaryProfile%2CfinancialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&ssl=true

So, v10 is replaced with v6 and "modules=module1,module2,module3" goes to "modules=module1&modules=module2&modules=module3" and the result is:

https://query2.finance.yahoo.com/v6/finance/quoteSummary/AMD?modules=summaryProfile&modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true

Dead code deleted

Cheers :)

**Comment by manuelwithbmw** [comment]
Sorry, I am unsure it is related, but since today I am unable to get the longName or shortName of any ticker from yfinance or yahooquery using the

**Comment by manuelwithbmw** [comment]
Sorry, I am unsure it is related, but since today I am unable to get the longName or shortName information from any ticker from yahooquery or yfinance using the below code:                                                                                                                                   
`tickerData = Ticker(tickerSymbol) 
Price = tickerData.price[tickerSymbol] 
print(Price['longName'])`

**Comment by ValueRaider** [comment]
@manuelwithbmw wrong place for posting yahooquery code

**Comment by ValueRaider** [comment]
I understand why someone posted "this doesn't work". Because this doesn't happen:

> https://query2.finance.yahoo.com/v6/finance/quoteSummary/AMD?modules=summaryProfile&modules=financialData&modules=quoteType&modules=defaultKeyStatistics&modules=assetProfile&modules=summaryDetail&ssl=true

Instead this:

> https://query2.finance.yahoo.com/v6/finance/quoteSummary/AMD?modules=summaryProfile&ssl=true

**Pull request merged**
