### PR TITLE
add get_insider_transaction_reported

### PR DESCRIPTION
**Pull request by h4x0rMadness-v2**
add get_insider_transaction_reported to fetch information [here](https://finance.yahoo.com/quote/MSFT/holders?p=MSFT)

image

### CODE REVIEW

**Comment by ValueRaider** [comment]
That class already has a `data` object, use that. And expose function via `Ticker` class.

**Comment by h4x0rMadness-v2** [comment]
> That class already has a `data` object, use that. And expose function via `Ticker` class.

Sure, could you take a look on the latest commit? thanks

**Comment by ValueRaider** [comment]
I looked and saw you ignored my review.

https://github.com/ranaroussi/yfinance/blob/88525abcbd9c1ab32b893d678a6c4fa8686bdf8e/yfinance/scrapers/holders.py#L10C1-L10C1

**Comment by ValueRaider** [comment]
Looking good. But please add unit test(s) to `tests/ticker.py`. Purpose is to fail if someone in future breaks your code.

Then to conform to #1084 if you don't mind:
- rebase to `dev` branch (plenty of guides online, or GPT4) and change target to `dev`
- git squash

**Comment by rickturner2001** [comment]
What's the status of this PR?

**Comment by h4x0rMadness-v2** [comment]
Added ut and changed target branch to dev, ready for review

**Comment by ValueRaider** [comment]
Where's the test?

**Pull request closed without merging**
