### PR TITLE
Feat/adding extra dependencies

### PR DESCRIPTION
**Pull request by JuliaLWang8**
Implemented extra dependencies as discussed in #1766.

This can be tested locally via the command `pip install -e .[extras]` by replacing extras with:
- `nospam`: requests dependencies for custom requests and testing
    -  requests_cache, requests_ratelimiter
- `repair`: for price repairing functionality 
    - scipy

Maybe also add to #1084 that `nospam` is required to run tests and link the Installation instructions in the readme.

### CODE REVIEW

**Comment by JuliaLWang8** [comment]
Regarding the naming, I think `nospam` makes sense concerning development because it's only needed for testing. However, since users could also install via the pip cmd to make custom requests (as in the readme), should we change it to reflect its use case?

**Comment by ValueRaider** [comment]
> should we change it to reflect its use case?

Isn't the use case same? Reduce spam on Yahoo.

**Comment by JuliaLWang8** [comment]
> > should we change it to reflect its use case?
> 
> Isn't the use case same? Reduce spam on Yahoo.

The way I interpreted the readme 'Smarter scraping' section was that the use case of `requests_cache` is a custom way to make requests via modifying User-agent. I guess there's also caching and the uses of `requests_ratelimiter` include the rate-limiting to avoid triggering Yahoo's blocker, so nospam makes sense.

**Comment by ValueRaider** [comment]
> The way I interpreted the readme 'Smarter scraping' section was that the use case of `requests_cache` is a custom way to make requests via modifying User-agent.

That's a README problem so my fault. To keep it concise I combined 2 examples:
- custom User-agent on a session
- replace `requests` with `requests-cache`

Maybe User-agent example should be removed.

**Comment by JuliaLWang8** [comment]
> Maybe User-agent example should be removed.

Should we change/remove it in the readme for this PR or just keep as is for now?

**Comment by ValueRaider** [comment]
Can lower scipy minimum to 1.6.3.

> Should we change/remove it in the readme for this PR or just keep as is for now?

I don't mind if in this PR. As you had confusion, probably you're best to decide whether/how to change.

**Comment by JuliaLWang8** [comment]
> Can lower scipy minimum to 1.6.3.
> I don't mind if in this PR. As you had confusion, probably you're best to decide whether/how to change.

Added these changes in my latest commit.

**Comment by ValueRaider** [comment]
I've made some 'personal preference' tweaks to README. If no complaint, then I'll merge.

**Comment by JuliaLWang8** [comment]
> I've made some 'personal preference' tweaks to README. If no complaint, then I'll merge.

Looks good to me!

**Pull request merged**
