### PR TITLE
Remove wrong comment

### PR DESCRIPTION
**Pull request by ymyke**

### CODE REVIEW

**Comment by ValueRaider** [comment]
I just noticed all your PRs are against `main`. Needs to be `dev. See #1084

**Comment by ymyke** [comment]
Done.

**Comment by ValueRaider** [comment]
You need to rebase your branch. See file changes.

**Comment by ymyke** [comment]
Now good?

**Comment by ValueRaider** [comment]
Click the "Files changed" tab

**Comment by ymyke** [comment]
Oh boy, I'm too dumb for this. No idea how all these changes ended up in my PR. Also can't get the rebase stuff to work. – Can I just start anew with my PRs, this time in the `dev` branch?

**Comment by ValueRaider** [comment]
You can, but I recommend you learn to rebase, it's a useful skill to have. Many guides don't emphasise that you must force-push after rebase. Try this: https://docs.gitlab.com/ee/topics/git/git_rebase.html

**Comment by ymyke** [comment]
Thanks, that link was helpful to understand a couple of things. Still wasn't able to get rid of the "garbage" in my PR above though. So ended up with a new one that uncovered a couple more issues in the README file. → #1216 – hope that works now. This PR here can be closed/removed.

**Pull request closed without merging**
