### PR TITLE
WIP: Better balance sheets

### PR DESCRIPTION
**Pull request by troels**
This patch creates a new method time_series_balance to fetch the long balance sheets from yahoo finance. Solves #709

```>>> yfinance.Ticker('MRNA').time_series_balance.to_markdown()```

|                                                                             |   2017-12-31 00:00:00 |   2018-12-31 00:00:00 |   2019-12-31 00:00:00 |   2020-12-31 00:00:00 |
|:----------------------------------------------------------------------------|----------------------:|----------------------:|----------------------:|----------------------:|
| Annual Accounts Payable                                                     |           2.0725e+07  |           3.121e+07   |           7.09e+06    |           1.8359e+07  |
| Annual Accounts Receivable                                                  |           1.3417e+07  |           2.2674e+07  |           9.462e+06   |           1.4008e+09  |
| Annual Accrued Interest Receivable                                          |           3.239e+06   |           7.909e+06   |           6.835e+06   |           9.725e+06   |
| Annual Accumulated Depreciation                                             |          -4.8031e+07  |          -6.4456e+07  |          -9.4584e+07  |          -1.19661e+08 |
| Annual Additional Paid In Capital                                           |           7.1679e+07  |           2.53816e+09 |           2.66943e+09 |           4.80185e+09 |
| Annual Allowance For Doubtful Accounts Receivable                           |         nan           |         nan           |         nan           |         nan           |
| Annual Assets Held For Sale Current                                         |         nan           |         nan           |         nan           |         nan           |
| Annual Available For Sale Securities                                        |           1.45851e+08 |           1.7299e+08  |           1.59987e+08 |           6.38848e+08 |
| Annual Buildings And Improvements                                           |           0           |           1.40442e+08 |           8.6414e+07  |           9.0201e+07  |
| Annual Capital Lease Obligations                                            |           1.5687e+07  |           3.3489e+07  |           1.32364e+08 |           2.07295e+08 |
| Annual Capital Stock                                                        |           1.17667e+09 |       33000           |       34000           |       40000           |
| Annual Cash And Cash Equivalents                                            |           1.34859e+08 |           6.58364e+08 |           2.35876e+08 |           2.62385e+09 |
| Annual Cash Cash Equivalents And Short Term Investments                     |           7.56029e+08 |           1.52143e+09 |           1.103e+09   |           4.60761e+09 |
| Annual Cash Equivalents                                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Cash Financial                                                       |         nan           |         nan           |         nan           |         nan           |
| Annual Commercial Paper                                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Common Stock                                                         |        6000           |       33000           |       34000           |       40000           |
| Annual Common Stock Equity                                                  |          -5.51365e+08 |           1.53024e+09 |           1.17481e+09 |           2.56138e+09 |
| Annual Construction In Progress                                             |           8.0759e+07  |           4.688e+06   |           3.222e+06   |           3.4507e+07  |
| Annual Current Accrued Expenses                                             |           5.4494e+07  |           5.5667e+07  |           4.0224e+07  |           3.74344e+08 |
| Annual Current Assets                                                       |           7.83223e+08 |           1.56301e+09 |           1.1288e+09  |           6.29788e+09 |
| Annual Current Capital Lease Obligation                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Current Debt                                                         |         nan           |         nan           |         nan           |         nan           |
| Annual Current Debt And Capital Lease Obligation                            |         nan           |         nan           |         nan           |         nan           |
| Annual Current Deferred Assets                                              |         nan           |         nan           |         nan           |         nan           |
| Annual Current Deferred Liabilities                                         |           9.6739e+07  |           1.09056e+08 |           6.331e+07   |           3.86719e+09 |
| Annual Current Deferred Revenue                                             |           9.6739e+07  |           1.09056e+08 |           6.331e+07   |           3.86719e+09 |
| Annual Current Deferred Taxes Assets                                        |         nan           |         nan           |         nan           |         nan           |
| Annual Current Deferred Taxes Liabilities                                   |         nan           |         nan           |         nan           |         nan           |
| Annual Current Liabilities                                                  |           1.91461e+08 |           2.22803e+08 |           1.43115e+08 |           4.38881e+09 |
| Annual Current Notes Payable                                                |         nan           |         nan           |         nan           |         nan           |
| Annual Current Provisions                                                   |         nan           |         nan           |         nan           |         nan           |
| Annual Defined Pension Benefit                                              |         nan           |         nan           |         nan           |         nan           |
| Annual Derivative Product Liabilities                                       |         nan           |         nan           |         nan           |         nan           |
| Annual Dividends Payable                                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Duefrom Related Parties Current                                      |         nan           |         nan           |         nan           |         nan           |
| Annual Duefrom Related Parties Non Current                                  |         nan           |         nan           |         nan           |         nan           |
| Annual Dueto Related Parties Current                                        |         nan           |         nan           |         nan           |         nan           |
| Annual Dueto Related Parties Non Current                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Employee Benefits                                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Financial Assets                                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Financial Assets Designatedas Fair Value Through Profitor Loss Total |         nan           |         nan           |         nan           |         nan           |
| Annual Finished Goods                                                       |         nan           |         nan           |         nan           |           1.29e+06    |
| Annual Fixed Assets Revaluation Reserve                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Foreign Currency Translation Adjustments                             |         nan           |         nan           |         nan           |         nan           |
| Annual Gains Losses Not Affecting Retained Earnings                         |          -1.157e+06   |          -1.32e+06    |           1.804e+06   |           3.004e+06   |
| Annual General Partnership Capital                                          |         nan           |         nan           |         nan           |         nan           |
| Annual Goodwill                                                             |         nan           |         nan           |         nan           |         nan           |
| Annual Goodwill And Other Intangible Assets                                 |         nan           |         nan           |         nan           |         nan           |
| Annual Gross Accounts Receivable                                            |         nan           |         nan           |         nan           |         nan           |
| Annual Gross Ppe                                                            |           1.87062e+08 |           2.76433e+08 |           3.82493e+08 |           5.06751e+08 |
| Annual Hedging Assets Current                                               |         nan           |         nan           |         nan           |         nan           |
| Annual Held To Maturity Securities                                          |         nan           |         nan           |         nan           |         nan           |
| Annual Income Tax Payable                                                   |         nan           |         nan           |         nan           |         nan           |
| Annual Interest Payable                                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Inventories Adjustments Allowances                                   |         nan           |         nan           |         nan           |         nan           |
| Annual Inventory                                                            |         nan           |         nan           |         nan           |           4.6527e+07  |
| Annual Invested Capital                                                     |          -5.51365e+08 |           1.53024e+09 |           1.17481e+09 |           2.56138e+09 |
| Annual Investment Properties                                                |         nan           |         nan           |         nan           |         nan           |
| Annual Investmentin Financial Assets                                        |           1.45851e+08 |           1.7299e+08  |           1.59987e+08 |           6.38848e+08 |
| Annual Investments And Advances                                             |           1.45851e+08 |           1.7299e+08  |           1.59987e+08 |           6.38848e+08 |
| Annual Investments In Other Ventures Under Equity Method                    |         nan           |         nan           |         nan           |         nan           |
| Annual Investmentsin Associatesat Cost                                      |         nan           |         nan           |         nan           |         nan           |
| Annual Investmentsin Joint Venturesat Cost                                  |         nan           |         nan           |         nan           |         nan           |
| Annual Investmentsin Subsidiariesat Cost                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Land And Improvements                                                |         nan           |         nan           |         nan           |         nan           |
| Annual Leases                                                               |           1.2222e+07  |           1.3741e+07  |           1.52426e+08 |           1.79901e+08 |
| Annual Liabilities Heldfor Sale Non Current                                 |         nan           |         nan           |         nan           |         nan           |
| Annual Limited Partnership Capital                                          |         nan           |         nan           |         nan           |         nan           |
| Annual Line Of Credit                                                       |         nan           |         nan           |         nan           |         nan           |
| Annual Loans Receivable                                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Long Term Capital Lease Obligation                                   |           1.5687e+07  |           3.3489e+07  |           1.32364e+08 |           2.07295e+08 |
| Annual Long Term Debt                                                       |         nan           |         nan           |         nan           |         nan           |
| Annual Long Term Debt And Capital Lease Obligation                          |           1.5687e+07  |           3.3489e+07  |           1.32364e+08 |           2.07295e+08 |
| Annual Long Term Equity Investment                                          |         nan           |         nan           |         nan           |         nan           |
| Annual Long Term Provisions                                                 |         nan           |         nan           |         nan           |         nan           |
| Annual Machinery Furniture Equipment                                        |           1.644e+07   |           2.0655e+07  |           2.2321e+07  |           2.508e+07   |
| Annual Minimum Pension Liabilities                                          |         nan           |         nan           |         nan           |         nan           |
| Annual Minority Interest                                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Net Debt                                                             |         nan           |         nan           |         nan           |         nan           |
| Annual Net Ppe                                                              |           1.39031e+08 |           2.11977e+08 |           2.87909e+08 |           3.8709e+08  |
| Annual Net Tangible Assets                                                  |           6.25296e+08 |           1.53024e+09 |           1.17481e+09 |           2.56138e+09 |
| Annual Non Current Accounts Receivable                                      |         nan           |         nan           |         nan           |         nan           |
| Annual Non Current Accrued Expenses                                         |         nan           |         nan           |         nan           |         nan           |
| Annual Non Current Deferred Assets                                          |         nan           |         nan           |         nan           |         nan           |
| Annual Non Current Deferred Liabilities                                     |           2.50515e+08 |           1.75358e+08 |           1.38995e+08 |           1.77419e+08 |
| Annual Non Current Deferred Revenue                                         |           2.42929e+08 |           1.65352e+08 |           1.38995e+08 |           1.77419e+08 |
| Annual Non Current Deferred Taxes Assets                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Non Current Deferred Taxes Liabilities                               |         nan           |         nan           |         nan           |         nan           |
| Annual Non Current Note Receivables                                         |         nan           |         nan           |         nan           |         nan           |
| Annual Non Current Pension And Other Postretirement Benefit Plans           |         nan           |         nan           |         nan           |         nan           |
| Annual Non Current Prepaid Assets                                           |         nan           |         nan           |         nan           |         nan           |
| Annual Notes Receivable                                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Ordinary Shares Number                                               |           3.24411e+08 |           3.28799e+08 |           3.36537e+08 |           3.98788e+08 |
| Annual Other Capital Stock                                                  |         nan           |         nan           |         nan           |         nan           |
| Annual Other Current Assets                                                 |         nan           |         nan           |         nan           |         nan           |
| Annual Other Current Borrowings                                             |         nan           |         nan           |         nan           |         nan           |
| Annual Other Current Liabilities                                            |           1.282e+06   |           3.464e+06   |           5.063e+06   |           3.3665e+07  |
| Annual Other Equity Adjustments                                             |          -1.157e+06   |          -1.32e+06    |           1.804e+06   |         nan           |
| Annual Other Equity Interest                                                |         nan           |         nan           |         nan           |         nan           |
| Annual Other Intangible Assets                                              |         nan           |         nan           |         nan           |         nan           |
| Annual Other Inventories                                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Other Investments                                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Other Non Current Assets                                             |           1.6384e+07  |           1.4176e+07  |           1.2722e+07  |           1.2933e+07  |
| Annual Other Non Current Liabilities                                        |           1.53e+06    |      258000           |      138000           |           1.853e+06   |
| Annual Other Payable                                                        |         nan           |         nan           |         nan           |         nan           |
| Annual Other Properties                                                     |           7.7641e+07  |           9.6907e+07  |           1.1811e+08  |           1.77062e+08 |
| Annual Other Receivables                                                    |         nan           |           1.0089e+07  |           4.093e+06   |         nan           |
| Annual Other Short Term Investments                                         |           6.2117e+08  |           8.63063e+08 |           8.67124e+08 |           1.98376e+09 |
| Annual Payables                                                             |           2.0725e+07  |           3.121e+07   |           7.09e+06    |           1.8359e+07  |
| Annual Payables And Accrued Expenses                                        |           7.5219e+07  |           8.6877e+07  |           4.7314e+07  |           3.92703e+08 |
| Annual Pensionand Other Post Retirement Benefit Plans Current               |           1.8221e+07  |           2.3406e+07  |           2.7428e+07  |           9.5247e+07  |
| Annual Preferred Securities Outside Stock Equity                            |           1.17666e+09 |           0           |         nan           |         nan           |
| Annual Preferred Shares Number                                              |         nan           |         nan           |         nan           |         nan           |
| Annual Preferred Stock                                                      |           1.17666e+09 |           0           |           0           |           0           |
| Annual Preferred Stock Equity                                               |           1.17666e+09 |         nan           |         nan           |         nan           |
| Annual Prepaid Assets                                                       |           9.587e+06   |           1.0401e+07  |           8.475e+06   |           2.32185e+08 |
| Annual Properties                                                           |           0           |           0           |           0           |           0           |
| Annual Raw Materials                                                        |         nan           |         nan           |         nan           |           3.6222e+07  |
| Annual Receivables                                                          |           1.6656e+07  |           3.0583e+07  |           1.6297e+07  |           1.41053e+09 |
| Annual Receivables Adjustments Allowances                                   |         nan           |         nan           |         nan           |         nan           |
| Annual Restricted Cash                                                      |      951000           |      595000           |           1.032e+06   |           1.032e+06   |
| Annual Restricted Common Stock                                              |         nan           |         nan           |         nan           |         nan           |
| Annual Retained Earnings                                                    |          -6.21893e+08 |          -1.00663e+09 |          -1.49645e+09 |          -2.24352e+09 |
| Annual Share Issued                                                         |           3.24411e+08 |           3.28799e+08 |           3.36537e+08 |           3.98788e+08 |
| Annual Stockholders Equity                                                  |           6.25296e+08 |           1.53024e+09 |           1.17481e+09 |           2.56138e+09 |
| Annual Tangible Book Value                                                  |          -5.51365e+08 |           1.53024e+09 |           1.17481e+09 |           2.56138e+09 |
| Annual Taxes Receivable                                                     |         nan           |         nan           |         nan           |         nan           |
| Annual Total Assets                                                         |           1.08449e+09 |           1.96215e+09 |           1.58942e+09 |           7.33675e+09 |
| Annual Total Capitalization                                                 |           6.25296e+08 |           1.53024e+09 |           1.17481e+09 |           2.56138e+09 |
| Annual Total Debt                                                           |           1.5687e+07  |           3.3489e+07  |           1.32364e+08 |           2.07295e+08 |
| Annual Total Equity Gross Minority Interest                                 |           6.25296e+08 |           1.53024e+09 |           1.17481e+09 |           2.56138e+09 |
| Annual Total Liabilities Net Minority Interest                              |           4.59193e+08 |           4.31908e+08 |           4.14612e+08 |           4.77538e+09 |
| Annual Total Non Current Assets                                             |           3.01266e+08 |           3.99143e+08 |           4.60618e+08 |           1.03887e+09 |
| Annual Total Non Current Liabilities Net Minority Interest                  |           2.67732e+08 |           2.09105e+08 |           2.71497e+08 |           3.86567e+08 |
| Annual Total Partnership Capital                                            |         nan           |         nan           |         nan           |         nan           |
| Annual Total Tax Payable                                                    |         nan           |         nan           |         nan           |         nan           |
| Annual Tradeand Other Payables Non Current                                  |         nan           |         nan           |         nan           |         nan           |
| Annual Trading Securities                                                   |         nan           |         nan           |         nan           |         nan           |
| Annual Treasury Shares Number                                               |         nan           |         nan           |         nan           |         nan           |
| Annual Treasury Stock                                                       |         nan           |         nan           |         nan           |         nan           |
| Annual Unrealized Gain Loss                                                 |         nan           |         nan           |         nan           |         nan           |
| Annual Work In Process                                                      |         nan           |         nan           |         nan           |           9.015e+06   |
| Annual Working Capital                                                      |           5.91762e+08 |           1.3402e+09  |           9.85689e+08 |           1.90907e+09 |

### CODE REVIEW

**Comment by Yunir** [comment]
Good! It will show "Ordinary Shares Number". With current version I cant get access to it via yfinance.

**Comment by chinmayandhare** [comment]
Hi Troels, can you suggest a change which will enable yfinance to pull Shares Outstanding data from income statements. It does not do that today when we pull balancesheets/cashflows/financials?

**Comment by EpsilonTal** [comment]
Hello,

This feature is very useful.
Any plans to merge it? 

Thanks.

**Comment by ValueRaider** [comment]
Another PR around the same time addresses this same problem - https://github.com/ranaroussi/yfinance/pull/776 . @EpsilonTal can you experiment with both and give opinion on which is better?

Also both ignore quarterly, probably that should be implemented too for a merge.

**Comment by ValueRaider** [comment]
Update: #774 has been merged into `dev` branch, so will soon ship in a PIP release.

**Pull request closed without merging**
