### PR TITLE
Fix many errors when executing _get_fundamentals on particular tickers

### PR DESCRIPTION
**Pull request by ohenley**
https://github.com/ranaroussi/yfinance/issues/172
https://github.com/ranaroussi/yfinance/issues/173
https://github.com/ranaroussi/yfinance/issues/163
https://github.com/ranaroussi/yfinance/issues/162

### CODE REVIEW

**Comment by ohenley** [comment]
To properly assess the robustness of yfinance, IMO, it should be tested against both nasdaq official ticker lists found here: ftp://ftp.nasdaqtrader.com/symboldirectory/

nasdaqlisted.txt
otherlisted.txt

**Comment by michel117** [comment]
Hi @ranaroussi , this pull request works, when I pulled it locally and ran a few scraping rounds. Could you merge it, or is something still missing (I see two quality checks failed).
Thanks!

**Comment by ohenley** [comment]
What is more important: greening 'quality checks' or writing bug-free code? 

For the last 2 months, I ran this branch against the 8k NASDAQ tickers on a daily basis and it did not fail once.

Anyway if code quality was truly a concern we, as a discipline, would write software in Ada, not Python. Sorry, it has to be told. :)

I suppose we can make this branch pass 'code checks' but I am not interested enough in Python or its Pythonic concerns to bother improving.

Anyway, thanks for chipping in Michel117.

**Comment by capellini** [comment]
> What is more important: greening 'quality checks' or writing bug-free code?

@ohenley I think the quality checks are there to prevent bugs in code, like the one you introduce here: https://github.com/ranaroussi/yfinance/pull/174/files#diff-69e424ccdc9dbd39c5d517098950e475R518

**Comment by ohenley** [comment]
> @ohenley I think the quality checks are there to prevent bugs in code, like the one you introduce here: https://github.com/ranaroussi/yfinance/pull/174/files#diff-69e424ccdc9dbd39c5d517098950e475R518

Hey Rob, thanks for chipping in to help me grow! Now I will help you with the basic stuff, the fundamentals:

"A software bug is an error, flaw or fault in a computer program or system that causes it to **produce an incorrect or unexpected result**," [https://en.wikipedia.org/wiki/Software_bug](Wikipedia)

```
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> old_search_str = '"|'
>>> print (old_search_str)
"|
>>> ticker = "ROB"
>>> search_str = '"|'.format(ticker)
>>> print (search_str)
"|
```

It changes nothing and therefore it is not a 'bug'. Oh, its trash, do not get me wrong, but it is totally valid loose ends good old Python. 

Like said before, I just bullied my way to make this codebase work, period. Now Pythonic, Pythoneer, Pythonist, Pythonista like you are welcome to replace the not so 'shiny pipes' using 'shiny pipe coverage' tools.

This PR works as it is tested extensively, daily. This useful repo is slowly becoming a PR festival with the author/s arguably ghosting it. 

In that context, if you detect useless code that 'red eye' this PR, why don't you just suggest a fix instead of necromancing an argument with me about the 'soundness' of 'code checker' over a fat finger toy language?

**Comment by capellini** [comment]
@ohenley do these lines of code do what you intend them to do?

https://github.com/ranaroussi/yfinance/blob/cf926fc9309f2cb317fd2808ef2d322927b4a953/yfinance/base.py#L319-L322

**Pull request closed without merging**
