### PR TITLE
Market summary

### PR DESCRIPTION
**Pull request by R5dan**
- New class for accessing the market summary of an area
    - As discussed in #2157 
    ```python
    import yfinance as yf
    summary = yf.MarketSummary(region)
    index = summary[index]
    status = index.status
    etc  
    ```
- New class for accessing data from `MarketSummary` to allow for types

### CODE REVIEW

**Comment by R5dan** [comment]
Don't pull yet, no docs or tests

**Comment by R5dan** [comment]
Ready

**Comment by ValueRaider** [comment]
Git squash commits then rebase to `dev` branch #1084 

But this might block squash: `Merge branch 'market-summary' ...`

**Comment by R5dan** [comment]
@ValueRaider sorry, not that good at git. Have tried but can you explain what commands to run. Otherwise I might just make more commits.

**Comment by ValueRaider** [comment]
> can you explain what commands to run

They're in the link

**Comment by R5dan** [comment]
> They're in the link

I know, I ran them. That's how I got to 21 commits

**Comment by ValueRaider** [comment]
When you get other people appearing in the commit history and you don't know why then just start over.

**Comment by R5dan** [comment]
Ok, sorry about not being very good at git. Should I still make the new branch of `main` or `dev`?

**Comment by R5dan** [comment]
@ValueRaider Closing this pr. Check out #2175

**Comment by ValueRaider** [comment]
Can you delete this branch? It will reduce clutter in https://github.com/ranaroussi/yfinance/network

**Pull request closed without merging**
