### PR TITLE
Add live tickers via yahoo finance websocket

### LINKED ISSUE #290: websocket support for ticker feeds
Thank you for the wonderful work on yfinance apis. So yahoo finance seems to be using websocket for streaming ticker updates. I didn't see that supported in the library. That would be an amazingly efficient way of getting ticker updates. Are there any thoughts on that? any work happening?

### PR DESCRIPTION
**Pull request by alparamonov**
yliveticker package encapsulates websocket client and protobuf decoding.

### CODE REVIEW

**Comment by alparamonov** [comment]
This pull request fixes #290

**Comment by HasanFaraaz** [comment]
@alparamonov  does this support streaming of Indian stock markets like BSE/NSE ? 
For ex:-  "ITC.NS" . If yes, what would be the format of it.

**Comment by alparamonov** [comment]
@HasanFaraaz for your example, just pass `ITC.NS` in the `ticker_names` array. When testing and not getting any data, check market hours.

**Comment by HasanFaraaz** [comment]
> @HasanFaraaz for your example, just pass `ITC.NS` in the `ticker_names` array. When testing and not getting any data, check market hours.

@alparamonov I ran the code but did not get any output. I tested this in market hours (9:50 AM IST) but there was no stream of data.

but yfinance
```
import yfinance as yf

# this function is called when new data is available
def on_new_data(data):
    print('received new data')
    print(data)

yf.Tickers("JPPOWER.NS").live(on_ticker=on_new_data)#tried ITC.NS also, but did not work
```
by yliveticker
```
import yliveticker


# this function is called on each ticker update
def on_new_msg(ws, msg):
    print(msg)


yliveticker.YLiveTicker(on_ticker=on_new_msg, ticker_names=["JPPOWER.NS"]) #tried ITC.NS also, but did not work
```

Also, I tried to see BTC price, I could not get stream of data for that too. It just appears to be stuck.

**Comment by alparamonov** [comment]
Tested just right now and got:

```json
{'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234315000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22914235, 'change': 1.6999969482421875, 'priceHint': 2}
{'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.89999389648438, 'timestamp': 1621234317000, 'marketHours': 1, 'changePercent': 0.7773822546005249, 'dayVolume': 22915440, 'change': 1.649993896484375, 'priceHint': 2}
{'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234320000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22916535, 'change': 1.6999969482421875, 'priceHint': 2}
```

Make sure you have the most recent version of the [package](https://github.com/yahoofinancelive/yliveticker).

**Comment by HasanFaraaz** [comment]
> Tested just right now and got:
> 
> ```json
> {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234315000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22914235, 'change': 1.6999969482421875, 'priceHint': 2}
> {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.89999389648438, 'timestamp': 1621234317000, 'marketHours': 1, 'changePercent': 0.7773822546005249, 'dayVolume': 22915440, 'change': 1.649993896484375, 'priceHint': 2}
> {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234320000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22916535, 'change': 1.6999969482421875, 'priceHint': 2}
> ```
> 
> Make sure you have the most recent version of the [package](https://github.com/yahoofinancelive/yliveticker).

@alparamonov by updating to latest version I am able to use the yliveticker library (which was not streaming before) & it gives the stream, but with yfinance there is no stream of data, it shows connection is open but no stream, I am using the code of tickers.py  from your 38bf894 
(also our trading time is over now just FYI).

Thanks for your responses :)

**Comment by HasanFaraaz** [comment]
> > Tested just right now and got:
> > ```json
> > {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234315000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22914235, 'change': 1.6999969482421875, 'priceHint': 2}
> > {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.89999389648438, 'timestamp': 1621234317000, 'marketHours': 1, 'changePercent': 0.7773822546005249, 'dayVolume': 22915440, 'change': 1.649993896484375, 'priceHint': 2}
> > {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234320000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22916535, 'change': 1.6999969482421875, 'priceHint': 2}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure you have the most recent version of the [package](https://github.com/yahoofinancelive/yliveticker).
> 
> @alparamonov by updating to latest version I am able to use the yliveticker library (which was not streaming before) & it gives the stream, but with yfinance there is no stream of data, it shows connection is open but no stream, I am using the code of tickers.py from your [38bf894](https://github.com/ranaroussi/yfinance/commit/38bf8942d39291d68f0e84ac3be4297bc9e98ebc)
> (also our trading time is over now just FYI).
> 
> Thanks for your responses :)

```

**Comment by HasanFaraaz** [comment]
> > Tested just right now and got:
> > ```json
> > {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234315000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22914235, 'change': 1.6999969482421875, 'priceHint': 2}
> > {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.89999389648438, 'timestamp': 1621234317000, 'marketHours': 1, 'changePercent': 0.7773822546005249, 'dayVolume': 22915440, 'change': 1.649993896484375, 'priceHint': 2}
> > {'id': 'ITC.NS', 'exchange': 'NSI', 'quoteType': 8, 'price': 213.9499969482422, 'timestamp': 1621234320000, 'marketHours': 1, 'changePercent': 0.8009408712387085, 'dayVolume': 22916535, 'change': 1.6999969482421875, 'priceHint': 2}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure you have the most recent version of the [package](https://github.com/yahoofinancelive/yliveticker).
> 
> @alparamonov by updating to latest version I am able to use the yliveticker library (which was not streaming before) & it gives the stream, but with yfinance there is no stream of data, it shows connection is open but no stream, I am using the code of tickers.py from your [38bf894](https://github.com/ranaroussi/yfinance/commit/38bf8942d39291d68f0e84ac3be4297bc9e98ebc)
> (also our trading time is over now just FYI).
> 
> Thanks for your responses :)

this is code i am usiong via yfinance

```
import yfinance as yf

# this function is called when new data is available
def on_new_data(data):
    print('received new data')
    print(data)

yf.Tickers("BTC=X").live(on_ticker=on_new_data)
```
P.S. big thanks for the nifty feature

**Comment by eabase** [comment]
This look pretty cool. Why hasn't it been merged?

**Comment by silvavn** [comment]
Functionality should be kept separate from yfinance. The library is also outdated and not working for many tickers.

**Pull request closed without merging**
