### PR TITLE
Feature: Fetch upto 200 news articles

### LINKED ISSUE #2075: Any way to get more news?
`ticker.news` seems to return 8 to 10 news articles.

However, Yahoo Finance can offer many more than 8 to 10 news articles per ticker: https://finance.yahoo.com/quote/MSFT/news/ (keep scrolling down).

Is there a way to get more than 8 to 10 news articles with yfinance?

### PR DESCRIPTION
**Pull request by dhruvan2006**
Resolves #2075 

## Changes
- Updated `get_news()` in `Ticker` to get up to 200 news articles (previously 8-10)
- The method now fetches news directly from the ticker's news page (https://finance.yahoo.com/quote/MSFT/latest-news/) instead of using the previous search based approach which was limiting

## Usage
```python
import yfinance as yf
news = yf.Ticker("MSFT").news
print(len(news))
```

## Warning
- **Breaking change**: The returned data structure/schema has changed. Further feedback is required on how to proceed.

### CODE REVIEW

**Comment by R5dan** [comment]
Could there be an error if the count is greater than 200? Even if it isn't raised but simply logged?

**Comment by R5dan** [comment]
Also the api returns a 404 response

**Comment by dhruvan2006** [comment]
Can you please show me what you did so I can try reproducing?

**Comment by R5dan** [comment]
> Can you please show me what you did so I can try reproducing?

Yes, sorry. After some more testing (to get the exact response) I realized I was sending `GET` requests and you were sending `POST`. However I am now getting `200`.

**Review by R5dan — APPROVED** [review]

**Comment by dhruvan2006** [comment]
@ValueRaider

**Comment by ValueRaider** [comment]
Can the default count be much lower e.g. 10 to reduce Yahoo server load? I know it's still one web request, but server-side probably different.

**Comment by dhruvan2006** [comment]
> Can the default count be much lower e.g. 10 to reduce Yahoo server load? I know it's still one web request, but server-side probably different.

Default for `get_news()` is now 10 articles.

**Pull request merged**
