### PR TITLE
Fix get_earnings_dates method

### PR DESCRIPTION
**Pull request by hjlgood**
Currently, get_earnings_dates doesn't work.

According to the below thread, it looks like YahooFinance changed their earnings format.
https://github.com/ranaroussi/yfinance/issues/1932#issuecomment-2518039027

I would like to add [Alex-Naxitus](https://github.com/Alex-Naxitus)'s code contribution to the original yfinance.

I've tested this code and get_earnings_dates works great.

### CODE REVIEW

**Comment by ValueRaider** [comment]
Works for me but there is a time shift. Here is something I have cached for `BP.L`:
```
                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date                                                     
2025-10-27 10:00:00+00:00           NaN           NaN          NaN
2025-07-28 11:00:00+01:00           NaN           NaN          NaN
2025-05-05 11:00:00+01:00           NaN           NaN          NaN
2025-02-04 10:00:00+00:00           NaN           NaN          NaN
2024-10-29 10:00:00+00:00           NaN           NaN          NaN
2024-07-30 07:00:00+01:00          0.16          0.17       0.0968
2024-05-07 11:00:00+01:00          0.18          0.16      -0.0914
2024-02-06 07:00:00+00:00          0.15          0.18       0.1842
2023-10-31 08:00:00+00:00          0.24          0.19      -0.2116
2023-08-01 11:00:00+01:00          0.21          0.15      -0.2754
2023-05-02 12:00:00+01:00          0.24          0.27       0.1066
2023-02-07 07:00:00+00:00          0.23          0.26       0.1304
```

And here what your code returns:
```
                           EPS Estimate  Reported EPS  Surprise (%)
Earnings Date                                                      
2025-10-26 20:00:00+00:00           NaN           NaN           NaN
2025-07-27 20:00:00+01:00           NaN           NaN           NaN
2025-05-04 20:00:00+01:00           NaN           NaN           NaN
2025-02-03 19:00:00+00:00          0.10           NaN           NaN
2024-10-28 20:00:00+00:00          0.13          0.14        0.0625
2024-07-29 20:00:00+01:00          0.16          0.17        0.0968
2024-05-06 20:00:00+01:00          0.18          0.16       -0.0914
2024-02-05 19:00:00+00:00          0.15          0.18        0.1842
2023-10-30 20:00:00+00:00          0.24          0.19       -0.2116
2023-07-31 20:00:00+01:00          0.21          0.15       -0.2754
2023-05-01 20:00:00+01:00          0.24          0.27        0.1066
2023-02-06 19:00:00+00:00          0.23          0.26        0.1304
```

Differences:
```
['0 days 14:00:00', '0 days 15:00:00', '0 days 15:00:00',
                '0 days 15:00:00', '0 days 14:00:00', '0 days 11:00:00',
                '0 days 15:00:00', '0 days 12:00:00', '0 days 12:00:00',
                '0 days 15:00:00', '0 days 16:00:00', '0 days 12:00:00']
```

Take the cached `2024-10-29 10am` vs fetched `2024-10-28 20pm` - cached is correct, fetch is early. https://otp.investis.com/clients/uk/bp_plc/rns/regulatory-story.aspx?cid=233&newsid=1879485

**Comment by Alex-Naxitus** [comment]
One thing I forgot to add in my comment are these modifications prior to line 624 : 
```
# Rename surprise column
 dates=dates.rename(columns={"Surpise (%)": "Surprise(%)"})
```
This would rename "Surprise (%)" (the new yahoo column name) into "Surprise(%)" (the old column name) thereby making it consistent with previous column naming conventions.

**Comment by Alex-Naxitus** [comment]
> Works for me but there is a time shift. Here is something I have cached for `BP.L`:
> 
> ```
>                            EPS Estimate  Reported EPS  Surprise(%)
> Earnings Date                                                     
> 2025-10-27 10:00:00+00:00           NaN           NaN          NaN
> 2025-07-28 11:00:00+01:00           NaN           NaN          NaN
> 2025-05-05 11:00:00+01:00           NaN           NaN          NaN
> 2025-02-04 10:00:00+00:00           NaN           NaN          NaN
> 2024-10-29 10:00:00+00:00           NaN           NaN          NaN
> 2024-07-30 07:00:00+01:00          0.16          0.17       0.0968
> 2024-05-07 11:00:00+01:00          0.18          0.16      -0.0914
> 2024-02-06 07:00:00+00:00          0.15          0.18       0.1842
> 2023-10-31 08:00:00+00:00          0.24          0.19      -0.2116
> 2023-08-01 11:00:00+01:00          0.21          0.15      -0.2754
> 2023-05-02 12:00:00+01:00          0.24          0.27       0.1066
> 2023-02-07 07:00:00+00:00          0.23          0.26       0.1304
> ```
> 
> And here what your code returns:
> 
> ```
>                            EPS Estimate  Reported EPS  Surprise (%)
> Earnings Date                                                      
> 2025-10-26 20:00:00+00:00           NaN           NaN           NaN
> 2025-07-27 20:00:00+01:00           NaN           NaN           NaN
> 2025-05-04 20:00:00+01:00           NaN           NaN           NaN
> 2025-02-03 19:00:00+00:00          0.10           NaN           NaN
> 2024-10-28 20:00:00+00:00          0.13          0.14        0.0625
> 2024-07-29 20:00:00+01:00          0.16          0.17        0.0968
> 2024-05-06 20:00:00+01:00          0.18          0.16       -0.0914
> 2024-02-05 19:00:00+00:00          0.15          0.18        0.1842
> 2023-10-30 20:00:00+00:00          0.24          0.19       -0.2116
> 2023-07-31 20:00:00+01:00          0.21          0.15       -0.2754
> 2023-05-01 20:00:00+01:00          0.24          0.27        0.1066
> 2023-02-06 19:00:00+00:00          0.23          0.26        0.1304
> ```
> 
> Differences:
> 
> ```
> ['0 days 14:00:00', '0 days 15:00:00', '0 days 15:00:00',
>                 '0 days 15:00:00', '0 days 14:00:00', '0 days 11:00:00',
>                 '0 days 15:00:00', '0 days 12:00:00', '0 days 12:00:00',
>                 '0 days 15:00:00', '0 days 16:00:00', '0 days 12:00:00']
> ```
> 
> Take the cached `2024-10-29 10am` vs fetched `2024-10-28 20pm` - cached is correct, fetch is early. https://otp.investis.com/clients/uk/bp_plc/rns/regulatory-story.aspx?cid=233&newsid=1879485
 
The new yahoo finance table now specifies Eastern Daylight Savings Time (EDT) or Eastern Standard Time (EST). Since one is 1 hour ahead of the other, this is why you get a difference.

**Comment by ValueRaider** [comment]
> Since one is 1 hour ahead of the other, this is why you get a difference.

The difference is 11-15 hours, not 1. So much it shifts the day.

**Comment by ValueRaider** [comment]
The fix for time shift is to respect the last field, not discard it. E.g. EDT/EST. I'll give you chance to integrate fix:

```
...
tzy = dates[cn].str.split(' ').str.get(-1)  # assume tz info is last field
tzy[tzy == 'EDT'] = 'US/Eastern'
...
```

Localize to `tzy`, then convert to local timezone `_get_ticker_tz`

**Comment by ValueRaider** [comment]
I've pushed fix for time-shift, looks good to me. One more day of testing then merge.

**Comment by hjlgood** [comment]
Thanks, I've been busy with other issues. Sorry for not responding promptly.

**Pull request merged**
