### PR TITLE
Allow specifying a custom requests session instance

### PR DESCRIPTION
**Pull request by occasionallydavid**
This allows caching, modifying the user agent, and finer grained control over proxy selection

### CODE REVIEW

**Comment by occasionallydavid** [comment]
Was this rejected?

**Comment by ranaroussi** [comment]
Screen Shot 2021-03-24 at 23 48 22

If you resolved these, I'd be happy to merge it :)

**Comment by occasionallydavid** [comment]
This should be mergeable now. I can't see the result of the merge test as you have marked the PR closed

**Comment by ranaroussi** [comment]
I've integrated the concept of your code to `0.1.58`

**Comment by occasionallydavid** [comment]
This is missing:

```diff
         # holders
         try:
-            holders = _pd.read_html(ticker_url+'/holders')
+            resp = self.session.get(ticker_url + '/holders')
+            resp.raise_for_status()
+            holders = _pd.read_html(resp.content)
         except Exception as e:
             holders = []
```

pd.read_html() is making an HTTP request underneath, it needs routed to the session

**Pull request closed without merging**
