### PR TITLE
Request optimization

### PR DESCRIPTION
**Pull request by fredrik-corneliusson**
I noticed that getting earnings did a lot of duplicate requests that made it quite slow.
When looking into this I found it easier to have one place to retrieve data in order to ease caching and speed up operations and reduce code duplication. Needs Python 3.6
As I use lru_cache I needed to drop Python versions before 3.6, update package metadata to reflect this.

### CODE REVIEW

**Comment by ValueRaider** [comment]
What speedup are you seeing?

**Comment by fredrik-corneliusson** [comment]
image
See before and after picture.
A good deal, at least running against the current dev branch

Also the number of unnecessary requests was removed because of cleaner code.
from:
```
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/holders HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query1.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query1.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=trailingPegRatio&period1=1652028925&period2=1667843725 HTTP/1.1" 200 363
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/financials HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/financials HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/financials HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=annualTotalRevenue,... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/financials HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=quarterlyTotalRevenue,quarterlyOperatingRevenue,... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/balance-sheet HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/balance-sheet HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=annualTotalAssets,...0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/balance-sheet HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=quarterlyTotalAssets,... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/cash-flow HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/cash-flow HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=annualCashFlowsfromusedinOperatingActivitiesDirect,... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/cash-flow HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query2.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query2.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=quarterlyCashFlowsfromusedinOperatingActivitiesDirect... HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/analysis HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/analysis HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
```
To:
```
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/holders HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): query1.finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://query1.finance.yahoo.com:443 "GET /ws/fundamentals-timeseries/v1/finance/timeseries/GOOGL?symbol=GOOGL&type=trailingPegRatio&period1=1652028653&period2=1667843453 HTTP/1.1" 200 363
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/financials HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
DEBUG:urllib3.connectionpool:https://finance.yahoo.com:443 "GET /quote/GOOGL/analysis HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): finance.yahoo.com:443
```

**Comment by fredrik-corneliusson** [comment]
Please note that it is specifically against the dev branch that has severe performance degradation for earnings (10s instead of under 3s in 0.1.85 in my tests), This patch cuts the time to get earnings to around 3.5s so still slower than 0.1.85. However the big win is that using this data-class will make performance bugs harder to introduce in the future.

**Comment by ValueRaider** [comment]
Great. My only comment is - is cache_maxsize set appropriately? I've not used lru_cache before so don't know if Ticker objects share same cache.

Those conflicts are easy to resolve, my recent merge introduced them.

**Comment by fredrik-corneliusson** [comment]
I just set it to something I figured would be ok. I did not want it to be unlimited.
Ticker objects share the same cache:
https://docs.python.org/3/library/functools.html#functools.lru_cache
"If a method is cached, the self instance argument is included in the cache"

**Comment by ValueRaider** [comment]
I've done some benchmarking - a loop of tickers accessing `info[]` or `cashflow`. I measure:
- 11 MB per ticker
- 1.7 MB per get() cache element
- 3.6 MB per get_json_data_stores() cache element

1000 elements in get_json_data_stores() cache will hit 5.3 GB

I also see no difference with the freezeargs enabled/disabled - what is purpose?

Benchmark in case interested:
```
process = psutil.Process(os.getpid())
mem_baseline = process.memory_info().rss
for tkr in tkrs:
	dat = yf.Ticker(tkr, session=session)
	# dat.info
	try:
		dat.cashflow
	except TypeError:
		pass
mem_used = process.memory_info().rss - mem_baseline
# Note: only works with freezeargs disabled
cs = dat._data.get_json_data_stores.cache_info()
print("get_json_data_stores() cache stats:")
print(cs)
print("get_json_data_stores() cache MB per # = {}".format(round(mem_used/1e6/cs.currsize, 1)))
```

**Comment by fredrik-corneliusson** [comment]
Good investigation, I decreased the cache size to 128 so it should now use less than 600 Mb, 
Most of the use of the cache is probably close together in time so I do not think it will harm performance.
The freezeargs is needed if you pass headers (a mutable dict) as caching relies on the hash function of the arguments when it saves it to cache and looks it up.

**Comment by fredrik-corneliusson** [comment]
I've lowered the cache size to 64 and fixed so cache_clear and cache_info should now work without disabling freezeargs.

**Comment by ValueRaider** [comment]
I'm happy to merge but think sensible to wait 24H in case you ruminate more changes.

**Pull request merged**
