### PR TITLE
Make ticker.info and option_chain works in edge cases

### PR DESCRIPTION
**Pull request by henrywoo**
The existing code doesn't work with some ticker like `AFGD`. This PR is to add more edge case and exception checks to make it work.

### CODE REVIEW

**Comment by PSU3D0** [comment]
Bump. Please merge this. Becomes quite problematic when fetching from large lists (S&P 500, etc)

**Comment by henrywoo** [comment]
Why close this? @ranaroussi

**Comment by ranaroussi** [comment]
The branch has conflicting files. I've reopened the pull request so you'll be able to investigate and solve this 😉

**Comment by ValueRaider** [comment]
This look dead, closing.

**Pull request closed without merging**
