### PR TITLE
Added support for getting growth estimates

### PR DESCRIPTION
**Pull request by coskos-ops**
Added support for getting growth estimates. Some people wanted this feature as seen in #1280 and #575. Added basic scraping logic for the analysis section. 

Only growth estimates are added for now but it can easily be extended to support some of the other data in that section. 

Added a test case to check if the growth estimates are properly being retrieved.

Edit: Updated the PR to save all the other information available on the analysis page. The code already scrapes all of the data on the analysis page so it is wasteful to discard all but one entry

### CODE REVIEW

**Comment by coskos-ops** [comment]
@bot-unit Should I save all the data available from the scraping? I only saved Growth Estimates because people were specifically asking for this feature. It would not be much work to extract the values of Earnings Estimate, Revenue Estimate, Earnings History, EPS Trend, and EPS revisions. They are already available in the analysis variable.

**Comment by coskos-ops** [comment]
@bot-unit I saved all the other data on the analysis page. No point discarding data for which we have already paid the tax of retrieving

**Comment by ValueRaider** [comment]
Benchmark with `time.perf_counter`?

**Comment by ValueRaider** [comment]
@coskos-ops Just looking at code there's probably opportunity to format types etc. Correct me if wrong. See `Ticker.get_earnings_dates` for inspiration.

**Comment by ValueRaider** [comment]
Changed target to branch `feature/growth-estimates` so someone else can finish. @dementedhedgehog

**Pull request merged**
