### PR TITLE
Feature: Add search feature

### PR DESCRIPTION
**Pull request by dhruvan2006**
This PR introduces a new search feature to the `yfinance` library that connects the functionality to search for tickers via the Yahoo Finance API.

I am open to further discussion and will be happy to complete the feature if the maintainers agree that this is a right addition to the package.

### CODE REVIEW

**Comment by ValueRaider** [comment]
Related: #1949

**Comment by dhruvan2006** [comment]
Should I complete the feature?

**Comment by ValueRaider** [comment]
You can add the feature, just also refactor any existing calls to search API.

**Comment by dhruvan2006** [comment]
## Summary
- The search functionality has been refactored from a function approach to a class based approach
- Refactored other classes that were using search features to now utilize the new `Search` class.
- Added unit tests
- Documentation added in `README` and `doc`

## Usage
```python
import yfinance as yf

# get list of quotes
quotes = yf.Search("AAPL", max_results=10).quotes

# get list of news
news = yf.Search("Google", news_count=10).news
```

## Test
```bash
python -m unittest tests.test_search
```

**Comment by ValueRaider** [comment]
Looks good. Can you squash the commits? #1084

**Comment by dhruvan2006** [comment]
Done

**Comment by dlflannery** [comment]
Is the Search class not in the latest pypi version (0.2.50) ?  I'm getting "Search is not an attribute of yfinance"

**Comment by ValueRaider** [comment]
Currently just `dev` branch, release coming soon.

**Pull request merged**
