### PR TITLE
#1195 Implemented a way to get the raw metadata

### PR DESCRIPTION
**Pull request by fredrik-corneliusson**

### CODE REVIEW

**Comment by ValueRaider** [comment]
I think fetching metadata separate from prices is wrong approach, should be returning what Yahoo returns with the prices. What if the second fetch is different? Yahoo uses a mix of data providers so possible.

I'm also not sure about hardcoding the interval, as metadata may be different with longer/shorter.

**Comment by fredrik-corneliusson** [comment]
Agree, but should there be a public accessor for metadata?
If so, what should be the default behavior if history has not run and no metadata has been extracted yet?
Maybe raise an error with information that history needs to be called first?
Also should it be called history_metadata instead of just metadata?

**Comment by ValueRaider** [comment]
> Also should it be called history_metadata instead of just metadata?

Definitely needs that context, "metadata" alone too vague.

All other questions apply to dividends and splits e.g. `get_dividends()`. Doesn't warn user if no prices fetched, but seems no one has complained so just copy that approach?

In case you hadn't noticed, @ymyke is implementing same feature  #1198, similar discussion.

**Comment by fredrik-corneliusson** [comment]
Closing this PR as it just duplicates #1198, will continue discussion there.

**Pull request closed without merging**
