### PR TITLE
Add Pyright type checking

### PR DESCRIPTION
**Pull request by marco-carvalho**
### Overview  
This PR introduces Pyright, a static type checker for Python, into the yfinance project. The purpose is to ensure type safety and improve code quality by identifying type-related issues during development.

### Benefits  
- **Type Safety**: Pyright helps in detecting type errors early in the development process, reducing runtime errors and improving reliability.  
- **Improved Documentation**: With type annotations, the code becomes more self-explanatory and easier to understand, aiding in code maintenance and collaboration.

### Changes  
- Created a new GitHub Action `pyright.yml` that triggers on pull requests to the master and main branches for automatic type checking.

### CODE REVIEW

**Comment by ValueRaider** [comment]
If this runs via Github actions, why does it need to be in requirements.txt?

**Comment by marco-carvalho** [comment]
@ValueRaider fixed!

**Comment by ValueRaider** [comment]
Does this require type hints in code to be useful?

**Comment by marco-carvalho** [comment]
Yes, Pyright will be most useful with type hints included in the code. While it can still check basic type correctness in code without type hints, its full potential is realized when explicit type annotations are used. This enhances its ability to catch type-related issues early during development, improving overall code quality and maintainability.

**Comment by ValueRaider** [comment]
I'm thinking move this to `dev` branch where others can add type hints #1084

**Pull request merged**
